### PR TITLE
[REFACTOR] Update mission model constructor to take planStart

### PR DESCRIPTION
**Pull request by patkenneally**
* **Tickets addressed:** NA
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
Updated mission model constructor to take planStart parameter. Updated tests similarly.

## Verification
Build, run test, use mission model in an Aerie deployment simulation context

## Documentation
None invalidated or needed

## Future work
None

### CODE REVIEW

**Review by mattdailis — APPROVED** [review]

**Review by pcrosemurgy — APPROVED** [review]

**Comment by pcrosemurgy** [comment]
Looks like this is failing due to the associated Merlin dep. being out of date? From the trace the generated mission model factory appears to be our old one (prior to the addition of an `Instant` parameter for plan start).

**Comment by pcrosemurgy** [comment]
Ahh, I assumed 0.12.3 had the PR to support an `Instant` plan start parameter. Looks like we just need to make a release with that PR incorporated, increment 0.12.3 in `build.gradle` here, and push :)

**Comment by pcrosemurgy** [comment]
Deps. are now set to `0.13.0`. When that release is made feel free to just re-run the failed CI tests here and the PR should be good to go.

**Comment by Twisol** [comment]
Can we / do we need to rebuild the JAR for this model to include in the `scheduler` tree for its tests?

**Pull request merged**
