### PR TITLE
Update Aerie Lander to Aerie 1.9.0

### PR DESCRIPTION
**Pull request by mattdailis**
Aerie lander remains our most realistic publicly available mission model, and we've let it fall behind Aerie proper. This PR brings Aerie lander up to the point where it compiles and passes tests against Aerie 1.9.0.

### CODE REVIEW

**Review by camargo — APPROVED** [review]
💯

**Comment by mattdailis** [comment]
Oops, just realized @Twisol had opened a similar PR several months ago - I will cross-reference that PR now.

**Comment by mattdailis** [comment]
I did a diff against #9 - @Twisol and I had made mostly the same changes verbatim. A few additional changes have occurred since #9 (notably SerializedValue combined `onReal` and `onInt` into `onNumeric`) which are included in this PR.

I am curious about the current state of scheduler tests that rely on aerie lander - my guess is they're built off of #9.

**Comment by mattdailis** [comment]
Looks like those tests were commented out in https://github.com/NASA-AMMOS/aerie/commit/91ce68c2#diff-513c291bf822aeb800bf37c1ef33b4b8b7ec3e5fe39888e484c3430aa0a052a0 I'll merge this PR, close #9, and make a mental note to follow up about the future of the aerie lander tests.

**Pull request merged**
